### ISSUE TITLE
Bug in Date Picker Component in Invoice Page

### ISSUE THREAD

**Issue by smilegupta** [InvincibleZeal/billbook#66]
![image](https://user-images.githubusercontent.com/38321072/130312537-34626b60-92ef-43e0-9cfb-8dd0091036d7.png)

Default behaviour of date picker, includes having a calendar opened.
Here i am not able to do the same.

**Comment by InvincibleZeal** [comment]
@smilegupta the date picker was suppressed on purpose since it shows another icon at the end of the date input.
![Screenshot_20210823_105059](https://user-images.githubusercontent.com/42371840/130394526-041246bd-8917-41fd-9e92-d1a886758de8.png)

On removing the css, the date input boxes would look like this.
![Screenshot_20210823_105120](https://user-images.githubusercontent.com/42371840/130394545-cf7c04b1-bef6-484e-a5dd-a0f55d8ace7d.png)
